### ISSUE TITLE
Question Regarding the Release of Source Code

### ISSUE THREAD

**Issue by lFelixC** [TrustAIRLab/importance-in-mlattacks#1]
First of all, thank you for your outstanding work on Machine Learning Attacks. I find this project extremely interesting. I was wondering if you have plans to open-source the code for this project in the near future. If possible, could you please share an estimated timeline? I am very eager to learn from your code and hope to contribute to its development.

Thank you for your time, and I look forward to your response!

**Comment by WenRuiUSTC** [comment]
Thanks for your interest! We’re planning to clean up and release the code by the end of November.

**Comment by WenRuiUSTC** [comment]
We have released the implementation for CIFAR-10, feel free to drop me an email at rui.wen@cispa.de if you encounter any issues.
